TIC-TAC-TOE (X-O) GAME

In [13]:
# Function to print the Tic-Tac-Toe board
def print_board(board):
    for i in range(0, 9, 3):
        print(board[i] + ' | ' + board[i+1] + ' | ' + board[i+2])
        if i < 6:
            print("---------")

# Function to check if there's a winner
def check_winner(board, player):
    win_conditions = [(0, 1, 2), (3, 4, 5), (6, 7, 8),  # Rows
                      (0, 3, 6), (1, 4, 7), (2, 5, 8),  # Columns
                      (0, 4, 8), (2, 4, 6)]             # Diagonals

    for condition in win_conditions:
        if board[condition[0]] == board[condition[1]] == board[condition[2]] == player:
            return True
    return False

# Minimax algorithm to evaluate the best move
def minimax(board, is_maximizing):
    if check_winner(board, 'X'):
        return -1  # Opponent (X) wins
    elif check_winner(board, 'O'):
        return 1   # We (O) win
    elif ' ' not in board:
        return 0   # It's a draw

    if is_maximizing:  # O's turn (our turn)
        best_score = -float('inf')
        for i in range(9):
            if board[i] == ' ':
                board[i] = 'O'
                score = minimax(board, False)
                board[i] = ' '  # Undo move
                best_score = max(score, best_score)
        return best_score
    else:  # X's turn (opponent's turn)
        best_score = float('inf')
        for i in range(9):
            if board[i] == ' ':
                board[i] = 'X'
                score = minimax(board, True)
                board[i] = ' '  # Undo move
                best_score = min(score, best_score)
        return best_score

# Function to determine the best move for O
def best_move(board):
    best_score = -float('inf')
    move = -1
    for i in range(9):
        if board[i] == ' ':
            board[i] = 'O'  # Try move
            score = minimax(board, False)
            board[i] = ' '  # Undo move
            if score > best_score:
                best_score = score
                move = i
    return move

# Main game loop
def play_game():
    board = [' ' for _ in range(9)]  # Initialize empty board
    while ' ' in board and not check_winner(board, 'X') and not check_winner(board, 'O'):
        # User places X
        while True:
            try:
                opponent_move = int(input("\nEnter the position (0-8) where you want to place X: "))
                if board[opponent_move] == ' ':
                    board[opponent_move] = 'X'
                    break
                else:
                    print("Position already taken, choose another spot.")
            except (ValueError, IndexError):
                print("Invalid input! Enter a number between 0 and 8.")
        print("\nOpponent (X) placed at:", opponent_move)
        print_board(board)
        if check_winner(board, 'X'):
            print("\nX wins!")
            break
        # Our turn (O) 
        move = best_move(board)
        if move == -1:
            print("\nIt's a draw!")
            break
        board[move] = 'O'
        print("\nYour turn (O) placed at:", move)
        print_board(board)
        
        if check_winner(board, 'O'):
            print("\nO wins!")
            break
            
    if ' ' not in board and not check_winner(board, 'X') and not check_winner(board, 'O'):
        print("\nIt's a draw!")
# Run the game
play_game()


Enter the position (0-8) where you want to place X:  0



Opponent (X) placed at: 0
X |   |  
---------
  |   |  
---------
  |   |  

Your turn (O) placed at: 4
X |   |  
---------
  | O |  
---------
  |   |  



Enter the position (0-8) where you want to place X:  3



Opponent (X) placed at: 3
X |   |  
---------
X | O |  
---------
  |   |  

Your turn (O) placed at: 6
X |   |  
---------
X | O |  
---------
O |   |  



Enter the position (0-8) where you want to place X:  2



Opponent (X) placed at: 2
X |   | X
---------
X | O |  
---------
O |   |  

Your turn (O) placed at: 1
X | O | X
---------
X | O |  
---------
O |   |  



Enter the position (0-8) where you want to place X:  7



Opponent (X) placed at: 7
X | O | X
---------
X | O |  
---------
O | X |  

Your turn (O) placed at: 5
X | O | X
---------
X | O | O
---------
O | X |  



Enter the position (0-8) where you want to place X:  8



Opponent (X) placed at: 8
X | O | X
---------
X | O | O
---------
O | X | X

It's a draw!

It's a draw!


APPLICATION CODE: SMART LOCKING SYSTEM

In [12]:
# Main selection logic
print("Select the mode: 'Owner' or 'Foreign'")
mode = input("Enter your choice: ").strip().lower()
if mode == "owner":
    # Owner Algorithm Code
    import random
    import numpy as np

    def print_grid(grid):
        print(grid)
    # Function to check if there's a winning combination (4 consecutive numbers horizontally, vertically, or diagonally)
    def check_winner(grid):
        # Check for horizontal wins
        for r in range(4):
            for c in range(1):
                if all(grid[r, c + i] != 0 and grid[r, c] == grid[r, c + i] for i in range(4)):
                    return True
    
        # Check for vertical wins
        for c in range(4):
            for r in range(1):
                if all(grid[r + i, c] != 0 and grid[r, c] == grid[r + i, c] for i in range(4)):
                    return True
    
        # Check for diagonal (down-right) wins
        for r in range(1):
            for c in range(1):
                if all(grid[r + i, c + i] != 0 and grid[r, c] == grid[r + i, c + i] for i in range(4)):
                    return True
    
        # Check for diagonal (up-right) wins
        for r in range(3, 4):
            for c in range(1):
                if all(grid[r - i, c + i] != 0 and grid[r, c] == grid[r - i, c + i] for i in range(4)):
                    return True
        return False
    
    # Function to place the owner's move (consecutive or non-consecutive)
    def place_move(owner_moves, grid):
        # Check if moves are consecutive (4 consecutive dice)
        if all(owner_moves[i] == owner_moves[i-1] + 1 for i in range(1, 4)):
            # Place all moves in a random column
            column = random.randint(0, 3)
            for move in owner_moves:
                for row in range(3, -1, -1):  # Find the lowest empty row in the column
                    if grid[row, column] == 0:
                        grid[row, column] = 1  # Place the "dice" (1)
                        break
            print("Phone unlocked!")
            return True
        else:
            # For non-consecutive moves, place two in the same column and the rest in different columns
            random.shuffle(owner_moves)  # Randomize order to mimic non-consecutive input
            
            # Step 1: Select a column to place two of the moves
            column = random.randint(0, 3)
            placed = 0
            for move in owner_moves[:2]:  # Place the first two moves in the same column
                for row in range(3, -1, -1):
                    if grid[row, column] == 0:
                        grid[row, column] = 1
                        placed += 1
                        break
    
            # Step 2: Place the remaining two moves in separate columns
            used_columns = [column]
            for move in owner_moves[2:]:
                placed_in_new_column = False
                while not placed_in_new_column:
                    new_column = random.randint(0, 3)
                    if new_column not in used_columns:  # Ensure new column is not already used
                        for row in range(3, -1, -1):
                            if grid[row, new_column] == 0:
                                grid[row, new_column] = 1
                                used_columns.append(new_column)
                                placed_in_new_column = True
                                break
                    if len(used_columns) == 4:  # If all columns are used
                        break
            
            # After placing non-consecutive moves, check if there's a winning combination
            if check_winner(grid):
                print("Game Over! A winning combination was formed.")
                return True
            
            print("Incorrect password. Try again.")
            return False
    
    # Function to reset the grid after each round
    def reset_grid():
        return np.zeros((4, 4), dtype=int)
    
    # Main game loop
    def play_game():
        rounds = 4  # Number of rounds for the owner to try unlocking the phone
        for round_num in range(1, rounds + 1):
            print(f"\nStarting Round {round_num}...")
            grid = reset_grid()  # Reset grid at the beginning of each round
            
            # Get player's moves for the round
            owner_moves = []
            for move_num in range(4):
                try:
                    player_move = int(input(f"Enter move {move_num + 1} (digit between 0 and 9): "))
                    if player_move < 0 or player_move > 9:
                        print("Invalid input. Please enter a number between 0 and 9.")
                        continue
                    owner_moves.append(player_move)
                except ValueError:
                    print("Invalid input. Please enter a valid digit.")
                    continue
    
            # Place the move and print the grid
            if place_move(owner_moves, grid):
                print_grid(grid)
                break
            else:
                print_grid(grid)
            
            # After each round, check if the grid is valid (no winning combination from non-consecutive moves)
            if check_winner(grid):
                print("Game Over! A winning combination was formed.")
                break
            
            if round_num == 4:
                print("Phone is locked, try again after 30 seconds.")
                break
    
    # Start the Owner game
    play_game()


elif mode == "foreign":
    import numpy as np
    import random
    
    # Initialize the 4x4 grid
    grid = np.zeros((4, 4), dtype=int)
    
    # Function to check if there's a winner (Player)
    def check_winner(grid, player):
        for r in range(4):
            for c in range(4):
                if c + 3 < 4 and all(grid[r, c + i] == player for i in range(4)):  # Check row
                    return True
                if r + 3 < 4 and all(grid[r + i, c] == player for i in range(4)):  # Check column
                    return True
                if r + 3 < 4 and c + 3 < 4 and all(grid[r + i, c + i] == player for i in range(4)):  # Diagonal (down-right)
                    return True
                if r - 3 >= 0 and c + 3 < 4 and all(grid[r - i, c + i] == player for i in range(4)):  # Diagonal (up-right)
                    return True
        return False
    
    # Function to check for possible winning moves for the player
    def check_possible_winning_moves(grid, player):
        winning_moves = []
        for c in range(4):
            for r in range(3, -1, -1):  # Check from bottom to top
                if grid[r, c] == 0:  # If there's an empty spot
                    grid[r, c] = player  # Simulate the player's move
                    if check_winner(grid, player):
                        winning_moves.append(c)
                    grid[r, c] = 0  # Undo the move
                    break
        return winning_moves
    
    # Function to block the player's winning move by the AI
    def ai_block_move(grid, player):
        winning_moves = check_possible_winning_moves(grid, player)
        if winning_moves:
            return winning_moves[0]
        return -1
    
    # Function to get AI's move
    def ai_move(grid):
        ai_winning_moves = check_possible_winning_moves(grid, 2)
        if ai_winning_moves:
            return ai_winning_moves[0]
        return ai_block_move(grid, 1)
    
    # Function to place the die in the grid
    def place_die(grid, column, player):
        for r in range(3, -1, -1):  # From bottom to top
            if grid[r, column] == 0:
                grid[r, column] = player
                return
    
    # Function to simulate a round of play
    def play_round(player_moves, grid, round_num):
        consecutive_sequence = []  # Track the sequence of player moves
    
        for move_num, player_move in enumerate(player_moves, start=1):
            print(f"Move {move_num} of Round {round_num}: Player's move (Digit {player_move})")
            
            # Check if player move extends a valid consecutive sequence
            if not consecutive_sequence or player_move == consecutive_sequence[-1] + 1:
                consecutive_sequence.append(player_move)
            else:
                consecutive_sequence = [player_move]  # Reset sequence if broken
    
            if round_num == 1 and len(consecutive_sequence) == move_num and move_num <= 3:
        # For Round 1: If user enters 3 consecutive numbers, put dice in the 0th column
                column = 0
            elif round_num == 2 and len(consecutive_sequence) == move_num and move_num <= 3:
        # For Round 2: If user enters 3 consecutive numbers, put dice in the 1st column
                column = 1
            elif round_num == 3 and len(consecutive_sequence) == move_num and move_num <= 3:
        # For Round 3: If user enters 3 consecutive numbers, put dice in the 2nd column
                column = 2
            elif round_num == 4 and len(consecutive_sequence) == move_num and move_num <= 3:
        # For Round 4: If user enters 3 consecutive numbers, put dice in the last row (row 3)
                column = move_num - 1  # Use the diagonal logic to place dice in last row
            else:
        # For non-consecutive numbers, place randomly in one of the columns
                column = np.random.choice([0, 1, 2, 3])
            place_die(grid, column, 1)  # Player's move (Computer places die)
            
            print("Grid after Player's (Computer's) move:")
            print(grid)
    
            if check_winner(grid, 1):
                print("Computer wins (Player's move)! Phone unlocked.")
                # Continue playing the round, but don't break the game
                # return True   # This would break the game, so we skip it
    
            # AI's move
            ai_column = ai_move(grid)
            place_die(grid, ai_column, 2)
    
            print("Grid after AI's move:")
            print(grid)
    
            if check_winner(grid, 2):
                print("AI wins!")
                # Continue playing the round, but don't break the game
                # return True   # This would break the game, so we skip it
    
        return False
 # Function to check if there are any remaining moves in the grid
    def check_remaining_moves(grid):
        for r in range(4):
            for c in range(4):
                if grid[r, c] == 0:  # If any cell is empty
                    return True
        return False

    
    # Main game loop
    def play_game():
        global grid
        rounds = 4
        for round_num in range(1, rounds + 1):
            print(f"\nStarting Round {round_num}...")
            player_moves = []
            for move_num in range(4):
                print(f"Enter move {move_num + 1} (digit between 0 and 9): ")
                try:
                    player_move = int(input())
                    if player_move < 0 or player_move > 9:
                        print("Invalid input. Please enter a number between 0 and 9.")
                        continue
                    player_moves.append(player_move)
                except ValueError:
                    print("Invalid input. Please enter a valid digit.")
                    continue
    
            # Play the round and print the result after each move
            play_round(player_moves, grid, round_num)
    
            # Print grid after round ends
            print("Grid after Round", round_num)
            print(grid)
    
            # Additional messages
            print("Entered Password is incorrect")
            print(f"Starting Round {round_num + 1}..." if round_num < 4 else "")
    
            if not check_remaining_moves(grid):
                print("No more moves possible. Game over.")
                break

            grid = np.zeros((4, 4), dtype=int)  # Reset grid for the next round
            print("=======================================")
    
        # After all rounds are completed
        print("Phone locked, try again in 30 seconds.")
    
    # Start the game
    play_game()

else:
    print("Invalid choice! Please restart the program and choose either 'Owner' or 'Foreign'.")

Select the mode: 'Owner' or 'Foreign'


Enter your choice:  Foreign



Starting Round 1...
Enter move 1 (digit between 0 and 9): 


 1


Enter move 2 (digit between 0 and 9): 


 4


Enter move 3 (digit between 0 and 9): 


 5


Enter move 4 (digit between 0 and 9): 


 9


Move 1 of Round 1: Player's move (Digit 1)
Grid after Player's (Computer's) move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]]
Grid after AI's move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 2]]
Move 2 of Round 1: Player's move (Digit 4)
Grid after Player's (Computer's) move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 1 2]]
Grid after AI's move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 2]
 [1 0 1 2]]
Move 3 of Round 1: Player's move (Digit 5)
Grid after Player's (Computer's) move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 2]
 [1 1 1 2]]
Grid after AI's move:
[[0 0 0 0]
 [0 0 0 2]
 [0 0 0 2]
 [1 1 1 2]]
Move 4 of Round 1: Player's move (Digit 9)
Grid after Player's (Computer's) move:
[[0 0 0 0]
 [0 0 0 2]
 [0 0 1 2]
 [1 1 1 2]]
Grid after AI's move:
[[0 0 0 2]
 [0 0 0 2]
 [0 0 1 2]
 [1 1 1 2]]
AI wins!
Grid after Round 1
[[0 0 0 2]
 [0 0 0 2]
 [0 0 1 2]
 [1 1 1 2]]
Entered Password is incorrect
Starting Round 2...

Starting Round 2...
Enter move 1 (digit between 0 and 9): 


 5


Enter move 2 (digit between 0 and 9): 


 4


Enter move 3 (digit between 0 and 9): 


 3


Enter move 4 (digit between 0 and 9): 


 2


Move 1 of Round 2: Player's move (Digit 5)
Grid after Player's (Computer's) move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]]
Grid after AI's move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 2]]
Move 2 of Round 2: Player's move (Digit 4)
Grid after Player's (Computer's) move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 1 0 2]]
Grid after AI's move:
[[0 0 0 0]
 [0 0 0 2]
 [0 0 0 1]
 [0 1 0 2]]
Move 3 of Round 2: Player's move (Digit 3)
Grid after Player's (Computer's) move:
[[0 0 0 0]
 [0 0 0 2]
 [0 0 0 1]
 [1 1 0 2]]
Grid after AI's move:
[[0 0 0 2]
 [0 0 0 2]
 [0 0 0 1]
 [1 1 0 2]]
Move 4 of Round 2: Player's move (Digit 2)
Grid after Player's (Computer's) move:
[[0 0 0 2]
 [0 0 0 2]
 [0 1 0 1]
 [1 1 0 2]]
Grid after AI's move:
[[0 0 0 2]
 [0 0 0 2]
 [0 1 0 1]
 [1 1 0 2]]
Grid after Round 2
[[0 0 0 2]
 [0 0 0 2]
 [0 1 0 1]
 [1 1 0 2]]
Entered Password is incorrect
Starting Round 3...

Starting Round 3...
Enter move 1 (digit between 0 and 9): 


 1


Enter move 2 (digit between 0 and 9): 


 2


Enter move 3 (digit between 0 and 9): 


 3


Enter move 4 (digit between 0 and 9): 


 4


Move 1 of Round 3: Player's move (Digit 1)
Grid after Player's (Computer's) move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]]
Grid after AI's move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 1 2]]
Move 2 of Round 3: Player's move (Digit 2)
Grid after Player's (Computer's) move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 1 2]]
Grid after AI's move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 1 2]
 [0 0 1 2]]
Move 3 of Round 3: Player's move (Digit 3)
Grid after Player's (Computer's) move:
[[0 0 0 0]
 [0 0 1 0]
 [0 0 1 2]
 [0 0 1 2]]
Grid after AI's move:
[[0 0 2 0]
 [0 0 1 0]
 [0 0 1 2]
 [0 0 1 2]]
Move 4 of Round 3: Player's move (Digit 4)
Grid after Player's (Computer's) move:
[[0 0 2 0]
 [0 0 1 1]
 [0 0 1 2]
 [0 0 1 2]]
Grid after AI's move:
[[0 0 2 2]
 [0 0 1 1]
 [0 0 1 2]
 [0 0 1 2]]
Grid after Round 3
[[0 0 2 2]
 [0 0 1 1]
 [0 0 1 2]
 [0 0 1 2]]
Entered Password is incorrect
Starting Round 4...

Starting Round 4...
Enter move 1 (digit between 0 and 9): 


 9


Enter move 2 (digit between 0 and 9): 


 3


Enter move 3 (digit between 0 and 9): 


 6


Enter move 4 (digit between 0 and 9): 


 1


Move 1 of Round 4: Player's move (Digit 9)
Grid after Player's (Computer's) move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]]
Grid after AI's move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 2]]
Move 2 of Round 4: Player's move (Digit 3)
Grid after Player's (Computer's) move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 0 2]]
Grid after AI's move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 2]
 [1 1 0 2]]
Move 3 of Round 4: Player's move (Digit 6)
Grid after Player's (Computer's) move:
[[0 0 0 0]
 [0 0 0 1]
 [0 0 0 2]
 [1 1 0 2]]
Grid after AI's move:
[[0 0 0 2]
 [0 0 0 1]
 [0 0 0 2]
 [1 1 0 2]]
Move 4 of Round 4: Player's move (Digit 1)
Grid after Player's (Computer's) move:
[[0 0 0 2]
 [0 0 0 1]
 [0 1 0 2]
 [1 1 0 2]]
Grid after AI's move:
[[0 0 0 2]
 [0 0 0 1]
 [0 1 0 2]
 [1 1 0 2]]
Grid after Round 4
[[0 0 0 2]
 [0 0 0 1]
 [0 1 0 2]
 [1 1 0 2]]
Entered Password is incorrect

Phone locked, try again in 30 seconds.
